### ISSUE TITLE
Helper script bug (register.sh)

### ISSUE THREAD

**Issue by dayrim** [juicycleff/ultimate-backend#121]
This is the output that i get from running register.sh It is expected write configs for all the services, yet it only does so for service-project.
```
$ ./scripts/register.sh
Service Registration system started
/src/bootstrap.yaml not found, skipping service
/src/bootstrap.yaml not found, skipping service
/src/bootstrap.yaml not found, skipping service
/src/bootstrap.yaml not found, skipping service
/src/bootstrap.yaml not found, skipping service
/src/bootstrap.yaml not found, skipping service
/src/bootstrap.yaml not found, skipping service
Registering io.ultimatebackend.srv.project
Success! Data written to: ultimatebackend/config/io.ultimatebackend.srv.project
Service Registration system completed
```
The issue is that PROJECT_DIR variable contains a hidden new line character /r at the end of string.

**Comment by dyllanwli** [comment]
I guess you installed the wrong version of yq. Please check out this: https://github.com/mikefarah/yq

**Comment by juicycleff** [comment]
@dayrim, I received a PR with this bug. I didn't review the PR in a hurry. please Ignore that file, I will delete it and everything with that PR

**Comment by juicycleff** [comment]
@dayrim thanks for point this out 👍
