### ISSUE TITLE
README.md:  Get started by registering a user on the admin gateway

### ISSUE THREAD

**Issue by maurosergiosilva** [juicycleff/ultimate-backend#126]
Mutation register return an activationLink, insteand of a token:

```
mutation register {  
  account {  
    register(input:{  
        firstname: "Alice"  
        lastname: "Bob"  
        email: "AliceBobsEmail@protonmail.com"  
        password: "supersecretpassword"  
    }) {  
      activationLink  
    }  
  }  
}  
```

**Comment by eduscrakozabrus** [comment]
I was confused about that, too. I was expecting a JWT token. The login is achieved by using cookies, api-admin sets them after successfully entering the login and password. But JWT is not implemented.

**Comment by juicycleff** [comment]
@maurosergiosilva it uses session cookie and activationLink is for activating your account
