### ISSUE TITLE
documentation  error - user registration

### ISSUE THREAD

**Issue by eduscrakozabrus** [juicycleff/ultimate-backend#128]
when i put:

mutation register {  
  account {  
    register(input:{  
        firstname: "Alice"  
        lastname: "Bob"  
        email: "AliceBobsEmail@protonmail.com"  
        password: "supersecretpassword"  
    }) {  
      token  
    }  
  }  
}  

Get:
{
  "error": {
    "errors": [
      {
        "message": "Cannot query field \"token\" on type \"AccountRegisterResponse\".",
        "locations": [
          {
            "line": 4,
            "column": 7
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Cannot query field \"token\" on type \"AccountRegisterResponse\".",

................

            ]
          }
        }
      }
    ]
  }
}

**Comment by eduscrakozabrus** [comment]
mutation register {  
  account {  
    register(input:{  
        firstname: "Alice"  
        lastname: "Bob"  
        email: "AliceBobsEmail@protonmail.com"  
        password: "supersecretpassword"  
    }) {  
        activationLink
    }  
  }  
}  

work with 'activationLink' at return

**Comment by juicycleff** [comment]
@eduscrakozabrus please format your code and issue
