### ISSUE TITLE
Serverless and message queue

### ISSUE THREAD

**Issue by gcherem** [juicycleff/ultimate-backend#136]
Thank you for this great project. I have a some questions:

1) How coupled it is to docker? I mean, is that possible to go serverless? If so, what do I need to change?
2) Is there a messaging queue like rabbit mq in the project?

Thanks in advance and keep up the good job!

**Comment by juicycleff** [comment]
There is NATS and EventStore.org, but you can switch nats to RabbitMQ. And it's not tied to docker. You can do pretty much whatever you want to do, but you just need to make sure your serverless can properly find other services
