### ISSUE TITLE
Consul Connection Refused

### ISSUE THREAD

**Issue by slh93** [juicycleff/ultimate-backend#143]
When I run the docker-compose command to build the services locally, each of the services output:

```
Error: consul: kv.get: connect ECONNREFUSED 127.0.0.1:8500
```

Any ideas why?

**Comment by slh93** [comment]
Oh I see your comment around issues with the consul docker container. I'm going to try setting up consul manually and seeing if that resolves it

**Comment by slh93** [comment]
I now see the comment around setting up consul manually. When I do so, I am not able to use the docker-compose command to build the other docker containers. Do you have a workaround to support running the ultimate-backend using docker?

**Comment by juicycleff** [comment]
@slh93 you can just remove consul from the docker-compose file and it will connect to your local running native consul agent
