### ISSUE TITLE
Event-Source - Alternatives? 

### ISSUE THREAD

**Issue by sharife3** [juicycleff/ultimate-backend#169]
Hi 

Firstly - awesome repo! Think this is really impressive. 

I wanted to ask - is there flexibility to use an alternative to event-store? 

What is supported in terms of using alternative event stores?  i see you have type: 'event-store'. If this was replaced with say 'nats' would you get the same functionality? 

Thank you

**Comment by juicycleff** [comment]
@sharife3 https://github.com/juicycleff/nestjs-event-store supports nats. In fact I prefer Nats over event store

**Comment by juicycleff** [comment]
https://github.com/juicycleff/nestjs-event-store will be reworked for v3

**Comment by sharife3** [comment]
Worked perfectly - by simply changing type to nats and adding the correct config options for nats to work!
