### ISSUE TITLE
Looks interesting

### ISSUE THREAD

**Issue by ujwal-setlur** [juicycleff/ultimate-backend#19]
Very much along the lines of what I am looking to do. How mature is this? Any docs? The README seems incomplete...

**Comment by juicycleff** [comment]
@ujwal-setlur I will be writing the docs soon as all the pieces are put in place. We have products working on the same architecture in one of the products in my company https://dimensionfour.io. all the stacks being used are proven and different patterns such as CQRS, GraphQL, Event sourcing are all proven practices and technology. But I think this is the first public project attempting graphql microservices with event sourcing. This architecture is now the standard in my current company

**Comment by paolog22** [comment]
looking good :) thanks
