### ISSUE TITLE
[QUESTION] Trouble understanding the flow of Gql context throughout services

### ISSUE THREAD

**Issue by bpofficial** [juicycleff/ultimate-backend#213]
My understanding currently is that the rpc services within the GraphQL context are serialized & sent to the microservices via RPC. However, this has confused me as the microservices would be running on separate containers & therefore not share the same memory space. There has to be a flaw in my understanding - Please advise

I'm currently working on a REST + TypeOrm migration of this project and would love to complete my implementation in order to offer it as an alternative to the GQL configuration (I can see from a previous issue that there are constraints howver I've solved them all in my implementation using db isolation)

Cheers :)

**Comment by juicycleff** [comment]
Hello @bpofficial we just pass the RPC client into the service. Makes it easy to access the client from the graphql context. It just makes for clean code. You don't have to adhere to it. feel free to initialize the client in your controller or service
