### ISSUE TITLE
TypeError: Cannot read property 'secret' of undefined

### ISSUE THREAD

**Issue by meodemsao** [juicycleff/ultimate-backend#218]
when i build service ```npx nest start service-account ```

log output 

```TypeError: Cannot read property 'secret' of undefined```

**Comment by tufail** [comment]
Hi @meodemsao ,

How did you fix this. I am also facing the same issue on window machine. Please help me

**Comment by meodemsao** [comment]
@tufail this my project https://github.com/meodemsao/nestjs-graphql-grpc-microservice-headeless-ecommerce
please refer that
