### ISSUE TITLE
Setup development environment

### ISSUE THREAD

**Issue by fabiofdsantos** [juicycleff/ultimate-backend#69]
What's the best way to setup the development environment?

**Comment by juicycleff** [comment]
Hi, @fabiofdsantos you mean locally or on a cloud?

**Comment by fabiofdsantos** [comment]
Locally. Are you using `scripts/development` to setup the dev environment in the cloud?

**Comment by juicycleff** [comment]
I don't see `scripts/development` used anywhere. However, the best way is to start up individual service your working.  You would need docker though for running some local MongoDB, event-store, and Redis.

My advice would be only run services you are working on or services that depend on another service like in the readme

**Comment by fabiofdsantos** [comment]
Ok, thanks!
Are you expecting to integrate it with Consul in the future?

**Comment by juicycleff** [comment]
@fabiofdsantos I have plans for Consul but its low hanging.

**Comment by fabiofdsantos** [comment]
@juicycleff this can be useful: https://github.com/nest-cloud/nestcloud/tree/master/packages/consul
