### ISSUE TITLE
Scope Request in websocket

### ISSUE THREAD

**Issue by chungchi300** [juicycleff/ultimate-backend#71]
I want to use this to build multi-tenant application with web socket that is original to use the Scope. Request for verifying the user in a socket on connection, but how I can get the request for module
 async handleConnection(socket: Socket) {

   const contextId = ContextIdFactory.getByRequest(???);

      const userService = await this.moduleRef.resolve(
        UsersService,
        contextId,
        { strict: false },
      );
}
My users service

@Injectable({ scope: Scope.REQUEST })
export class UsersService {
}

Again, great library~

**Comment by juicycleff** [comment]
@chungchi300 I am sorry at this time, you cant use websocket with apollo federated services. However I am rewriting the services to use GRPC internally and just have one graphql api. It will be out soon. It comes with support for Consul and consul managed configurations

**Comment by juicycleff** [comment]
@chungchi300 it is now possible with the next ntanch
