### ISSUE TITLE
lerna / yarn workspaces?

### ISSUE THREAD

**Issue by GrayStrider** [juicycleff/ultimate-backend#72]
Surprised not to see it here, any comments

**Comment by juicycleff** [comment]
@GrayStrider I am not using Lerna or workspaces because I've had issues with libraries depending on different versions of an npm package and can be problematic. I do prefer using a single package Json

**Comment by GrayStrider** [comment]
It's more about not having a huge `node_modules` in every package

**Comment by GrayStrider** [comment]
I see, I haven't tried nest cli monorepo mode yet!
