### ISSUE TITLE
docker-compose file for automatic development

### ISSUE THREAD

**Issue by mimani68** [juicycleff/ultimate-backend#74]
Hi all;
I ran each service as suggested in the docs but its hard to run all then individually, i suggest to use **automatic tools for development** that run database and all service tied together.
For example simple docker-compose that launch all service and check health check of them.

Reference: 
* https://devcenter.heroku.com/articles/local-development-with-docker-compose

**Comment by juicycleff** [comment]
@mimani68 thanks for the feedback, I am working on the DevOps part and rewriting it, and sure I will do that, even setting the config file in consul on service first run

**Comment by cermakondrej** [comment]
@juicycleff are you doing this in the `next` branch aswell :) ? I would imagine great boilerplate would be just to run `docker-compose up` and everything would be ready with some cont-init scripts (eg s6-overlay)

**Comment by juicycleff** [comment]
@cermakondrej there's support for that now

**Comment by iamonuwa** [comment]
@juicycleff I've tried running this locally, it takes long time to run. Can we have `docker compose` for development with live reload?
