### ISSUE TITLE
Error: "Cursor" defined in resolvers, but not in schema while running api-admin (2.0.0-alpha.1)

### ISSUE THREAD

**Issue by shajeeck** [juicycleff/ultimate-backend#75]
version : 2.0.0-alpha.1

Followed tutorial and after starting all services tried to start **api-admin**, getting following error

> $ node dist/apps/api-admin/main.js
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [NestFactory] Starting Nest application...
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] BootModule dependencies initialized +130ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] GlobalClientModule dependencies initialized +3ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] CoreModule dependencies initialized +1ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] PassportModule dependencies initialized +1ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] WebhooksModule dependencies initialized +2ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] NotificationsModule dependencies initialized +1ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] HttpModule dependencies initialized +4ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] PlansModule dependencies initialized +4ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] ConsulModule dependencies initialized +17ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] AppModule dependencies initialized +2ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] RolesModule dependencies initialized +3ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] CqrsModule dependencies initialized +3ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] TenantsModule dependencies initialized +3ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] BillingsModule dependencies initialized +1ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] CardsModule dependencies initialized +2ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] TenantMembersModule dependencies initialized +2ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] UsersModule dependencies initialized +2ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] AccessTokenModule dependencies initialized +2ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +2ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [ConfigModule] ConfigModule initialized
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] ConfigModule dependencies initialized +3ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] AccountsModule dependencies initialized +6ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] GraphQLModule dependencies initialized +3ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [ServiceModule] ServiceModule initialized
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] ServiceModule dependencies initialized +5ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [InstanceLoader] LoadbalanceModule dependencies initialized +2ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [RoutesResolver] AppController {}: +165ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [RouterExplorer] Mapped {, GET} route +6ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [RoutesResolver] AccountsController {/account}: +2ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [RouterExplorer] Mapped {/account/facebook, GET} route +4ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [RouterExplorer] Mapped {/account/google, GET} route +2ms
[Nest] 12324   - 04/15/2020, 1:03:14 AM   [RouterExplorer] Mapped {/account/github, GET} route +2ms
(node:12324) UnhandledPromiseRejectionWarning: Error: "Cursor" defined in resolvers, but not in schema
(node:12324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by shajeeck** [comment]
@juicycleff really an awesome project! Any help with above issue? Because of no documentations its getting get track for a newbie :)

**Comment by juicycleff** [comment]
@shajeeck I fixed it in the latest PR. I believe it's a regression issue with the `@nestjs/graphql` scaler feature.
