### ISSUE TITLE
Build Error (billing service)  : Type is not assignable in billings.controller.ts(134,7)

### ISSUE THREAD

**Issue by shajeeck** [juicycleff/ultimate-backend#82]
**version : 2.0.0-alpha.2**

running `npx nest build service-billing ` gives an error

> ERROR in XX/ultimate-backend/apps/service-billing/src/billings/billings.controller.ts
ERROR in XX/ultimate-backend/apps/service-billing/src/billings/billings.controller.ts(134,7):
TS2322: Type 'string | ObjectId' is not assignable to type 'string'.
  Type 'ObjectId' is not assignable to type 'string'.

quick fix
**(134,7)** `tenantId: tenant?.id as string`

**Comment by shajeeck** [comment]
access service also gives build error in 

> access-token.controller.ts(36,75)

**Comment by juicycleff** [comment]
@shajeeck yeah, I noticed the linter error. I fixed them in my recent PR. Thanks
