### ISSUE TITLE
[v2.0.0-alpha.2] Error in function setRpcContext (set-grpc-context.helpers.ts)

### ISSUE THREAD

**Issue by shajeeck** [juicycleff/ultimate-backend#97]
In function setRpcContext below given block is repeated 2 times and also the if condition given doesn't produce expected result

`if (ctx.isAuthenticated) {
    meta.set('user', JSON.stringify(ctx.getUser()));
  }
`

the function inside if condition is not invoked

**fix**

 is `ctx.isAuthenticated() ` correct usage?

**Comment by juicycleff** [comment]
That was just duplicate code, and I deleted it. What behavior are you talking about? setRpcContext set's the current user entity in the RPC context so services can be aware of the current logged in user

**Comment by shajeeck** [comment]
The  function inside `if` condition is not properly invoked, missing brackets `()`
_if ( ctx.isAuthenticated_ **()**  _)_
